// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    throw UnsupportedError('This Firebase app is configured for web only.');
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCG4CTBle-Gq-DOMTcueopfELxB07hs1Ys',
    appId: '1:36936390054:web:2094daeddbdf8bf3166b67',
    messagingSenderId: '36936390054',
    projectId: 'pantry-tracker-4bc45',
    authDomain: 'pantry-tracker-4bc45.firebaseapp.com',
    storageBucket: 'pantry-tracker-4bc45.firebasestorage.app',
    measurementId: 'G-VCG11VCF78',
  );
}
