// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCG4CTBle-Gq-DOMTcueopfELxB07hs1Ys',
    appId: '1:36936390054:web:2094daeddbdf8bf3166b67',
    messagingSenderId: '36936390054',
    projectId: 'pantry-tracker-4bc45',
    authDomain: 'pantry-tracker-4bc45.firebaseapp.com',
    storageBucket: 'pantry-tracker-4bc45.firebasestorage.app',
    measurementId: 'G-VCG11VCF78',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMaNZtjtAIZBjVZyls4KSXfIj9dw5atlc',
    appId: '1:36936390054:android:06a34627abef7e2f166b67',
    messagingSenderId: '36936390054',
    projectId: 'pantry-tracker-4bc45',
    storageBucket: 'pantry-tracker-4bc45.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzG3RIukb7G81rZahVFkr6QjoSd3EUpfU',
    appId: '1:36936390054:ios:2d5ae7cce744e502166b67',
    messagingSenderId: '36936390054',
    projectId: 'pantry-tracker-4bc45',
    storageBucket: 'pantry-tracker-4bc45.firebasestorage.app',
    iosBundleId: 'com.drewbrandt.pantryInventory',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCG4CTBle-Gq-DOMTcueopfELxB07hs1Ys',
    appId: '1:36936390054:web:399b1b4892678985166b67',
    messagingSenderId: '36936390054',
    projectId: 'pantry-tracker-4bc45',
    authDomain: 'pantry-tracker-4bc45.firebaseapp.com',
    storageBucket: 'pantry-tracker-4bc45.firebasestorage.app',
    measurementId: 'G-SNTTVNKQ8X',
  );
}
